### ISSUE TITLE
可能存在的问题

### ISSUE THREAD

**Issue by wzltfsi** [xiaoweiChen/Template-Metaprogramming-with-CPP#1]
hi xiaowei , 首先十分感谢您无私的奉献，为国内C++的开发者提供国外优秀C++书籍的中文翻译
在此提出几个有可能的翻译问题，也是尽一份绵薄之力

******* 1   中文译本的 91 页  
《注释中有几个参考点。[1] 声明了一个名为 parser 的类模板，[2] 定义一个名为 handle 的函数，
该函数以 double 作为参数。类模板的定义在 [3]。该类包含一个名为 run 的方法，该方法调用一个
名为 handle 的函数，其参数值为 42，位于 [4]。》

未在程序里发现   名为 run 的方法

******* 2 中文译本的 121 页  
《这个实现使用 std::forward 将左值作为左值传递，将右值作为右值传递，同样适用于可变函数
模板。下面是 std::make_unique 函数的概念实现，其创建了一个 std::unique_ptr 对象:》
这段话下面的程序估计是粘贴错误了，粘贴的程序和上面的程序一模一样，对比了原书确认粘贴错了
应该的程序是

template<typename T, typename... Args>
std::unique_ptr<T> make_unique(Args&&... args)
{
   return std::unique_ptr<T>(
           new T(std::forward<Args>(args)...));
}

*******3 中文译本的 144 页  
最下面的程序
template <
2 typename T,
3 typename=typenamestd::enable_if_t<    // 没有空格
4 std::is_integral_v<T>>>
5 struct integral_wrapper

******* 4 中文译本的 152 页
图标中的 ：
《   is_empty C++11
是否为空类型。空类型是一种类类型 (不是联合体)，
是否为空类型。空类型是一种类类型 (不是联合体)，  // 重复了
没有虚函数，没有虚基类，也没有非空基类。 》

******* 5 中文译本的 202 页
图标中的 ：
《  注意，基类模板中的成员函数和派生类中调用的成员函数具有不同的名称。否则，若具有相同称，因为它们不再是虚函数了，派生类成员函数将隐藏基类成员，、。》   // 标点符号问题

******* 6
整个翻译里面 很多处 stirng 都是 作为 粗体蓝色表示，显得很突兀

**Comment by xiaoweiChen** [comment]
抱歉，今天才看到你的issue。

1. 这里应该是原书，或者我这边获取到的原书错误。run应该是代码中parser结构体类的parse()成员函数。
2. 这个没问题
3. 我拿到的原书中这里没有空格
4. 这个没问题
5. 这个没问题
6. 样式问题，这个我不予解决，因为只是业余翻译，所以不会对阅读者的阅读体验进行优化。而且，代码开源，可以根据自己的喜好进行修改。
